# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- DevStar

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'
  
- script: |
    rm -rf node_modules && npm install -g @angular/cli 
    
- task: Npm@1
  inputs:
    command: 'install'
    customEndpoint: 'gatornpm'

#- script:   lsc build site
- script: npm run build:prod --dest='dist/gator'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    #azureSubscription: 'Axle - MPN - Rafat(1c2b7486-ccf8-41e0-bdfa-ab797f153518)'
    azureSubscription: 'Rafat-Gator(87f0d394-7e24-4e5b-93b2-c48e695febe7)'
    appType: 'webApp'
    WebAppName: 'Dev-Star'
    packageForLinux: '$(System.DefaultWorkingDirectory)/dist/gator'
